# 1. install all dependencies
FROM node:20-alpine AS deps
WORKDIR /app
ENV HUSKY=0

# copy all workspaces mainifest
COPY package.json package-lock.json ./
COPY server/package.json ./server/
COPY shared/package.json ./shared/
COPY client/package.json ./client/

RUN --mount=type=cache,target=/root/.npm \
    npm ci --fetch-retries=5 --fetch-retry-maxtimeout=120000

# 2 build
FROM deps AS build
COPY . . 

# server + shared 
RUN npm run build -w shared && npm run build -w server

# 3 prod runtime
FROM node:20-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
ENV HUSKY=0

# copy manifests and compiled outputs for monorepo resolution
COPY package.json package-lock.json ./
COPY shared/package.json ./shared/
COPY --from=build /app/shared/dist ./shared/dist
COPY server/package.json ./server/
COPY --from=build /app/server/dist ./server/dist
COPY server/migrations ./server/migrations
COPY server/scripts ./server/scripts

RUN --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev --fetch-retries=5 --fetch-retry-maxtimeout=120000

EXPOSE 3000
CMD ["node", "server/dist/src/server.js"]
