CREATE TABLE public.refresh_tokens (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    jti character varying(36) NOT NULL,
    token_hash text NOT NULL,
    user_id uuid NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    issued_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.users (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(150) NOT NULL,
    password text NOT NULL,
    is_active boolean DEFAULT false,
    verification_code character varying(100),
    verification_code_expiry_time timestamp without time zone,
    registration_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    last_login timestamp without time zone,
    is_super_user boolean DEFAULT false,
    oauth_provider character varying(50),
    oauth_id character varying(255),
    oauth_access_token text,
    oauth_refresh_token text,
    oauth_token_expires_at timestamp without time zone,
    reset_password_token character varying(255),
    reset_passsword_token_expiry_time timestamp with time zone,
    profile_pic text,
    last_login_method character varying(20),
    is_two_factor_enabled boolean DEFAULT false,
    two_factor_secret character varying(255),
    is_deleted boolean DEFAULT false,
    last_ip character varying(45),
    last_browser text,
    last_os text,
    last_device text,
    last_location text,
    last_country text,
    last_city text
);
